name: CPH2083

on:
  workflow_dispatch:
    inputs:
      repository: { description: 'Repo', required: true, default: 'malkist01/A11K' }
      branch: { description: 'Branch', required: true, default: 'ksu' }
      defconfig: { description: 'Defconfig', required: true, default: 'stock_defconfig' }

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.branch }}
        submodules: recursive
        
    - name: Prepare timezone 
      run: |
            sudo rm /etc/localtime
            sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
   
    - name: Install Dependencies
      run: |
            sudo apt-get update -qq
            sudo apt-get install -y --no-install-recommends \
            git curl wget \
            build-essential gcc make \
            bc bison flex \
            libssl-dev libelf-dev \
            libncurses5-dev \
            python3 \
            zip unzip \
            cpio \
            ccache \
            binutils-aarch64-linux-gnu \
            binutils-arm-linux-gnueabihf \
            lld \
            rsync \
            clang
   
    - name: Clone Toolchains
      run: |
            wget https://github.com/ZyCromerZ/Clang/releases/download/10.0.1-20220724-release/Clang-10.0.1-20220724.tar.gz -O clang.tar.gz
            mkdir -p clang && tar -xf clang.tar.gz -C clang
            git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git -b lineage-19.1 --depth=1 gcc64
            git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git -b lineage-19.1 --depth=1 gcc32
 
    - name: Setup Environment
      run: |
            echo "BUILD_TIME=$(TZ=Asia/Jakarta date "+%d%m%Y-%H%M")" >> $GITHUB_ENV
            echo "CLANG_PATH=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV
            echo "GCC64_PATH=$GITHUB_WORKSPACE/gcc64" >> $GITHUB_ENV
            echo "GCC32_PATH=$GITHUB_WORKSPACE/gcc32" >> $GITHUB_ENV

    - name: Clone kernelSU-Next
      run: |
           echo "CONFIG_KSU=y" >> ./arch/arm64/configs/stock_defconfig
           echo "CONFIG_KPM=y" >> ./arch/arm64/configs/stock_defconfig
           echo "CONFIG_KALLSYMS=y" >> ./arch/arm64/configs/stock_defconfig
           echo "CONFIG_KALLSYMS_ALL=y" >> ./arch/arm64/configs/stock_defconfig
           curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/refs/heads/main/kernel/setup.sh" | bash -s main
           curl -LSs "https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Rekernel/rekernel_patches.sh" | bash -s 
           wget https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Patch/susfs_patch_to_4.9.patch
           patch -p1 < susfs_patch_to_4.9.patch
           curl -LSs "https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/susfs_inline_hook_patches.sh" | bash -s  

    - name: Build Kernel
      run: |
            export ARCH=arm64
            export PATH="$CLANG_PATH/bin:$GCC64_PATH/bin:$GCC32_PATH/bin:$PATH"
            export KBUILD_BUILD_USER=user-tobrut
            export KBUILD_BUILD_HOST=exotic-host
            export KBUILD_COMPILER_STRING="$$CLANG_PATH/clang"
            make O=out ARCH=arm64 stock_defconfig 
            make -j$(nproc --all) O=out ARCH=arm64 HOSTCC=clang DTC=dtc \
              CLANG_TRIPLE=$CLANG_PATH/aarch64-linux-gnu- \
              CROSS_COMPILE=$GCC64_PATH/bin/aarch64-linux-android- \
              CROSS_COMPILE_ARM32=$GCC32_PATH/bin/arm-linux-gnueabi-         
            mv out/.config out/stock_defconfig.txt

    - name: Clone Anykernel3
      run: |
            git clone -b CPH2083 --depth=1 https://github.com/malkist01/anykernel3 AnyKernel3
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
            cd AnyKernel3
            zip -r "../Teletubies-${{ env.BUILD_TIME }}.zip" *

    - name: Upload Flashable zip
      uses: actions/upload-artifact@v4
      with:
        name: Teletubies-CPH2083-${{ env.BUILD_TIME }}
        path: AnyKernel3/*
